### ISSUE TITLE
It's working 100% No Scam

### ISSUE THREAD

**Issue by GDBOI101** [NrgCristi/MemoryLeakFixer#1]
i tried it and it worked lol, thanks for the help @NrgCristi i fixed the memory leak issue with my fortnite 4.5 build ur the best coder thank you

**Comment by NrgCristi** [comment]
idk

lun., 3 oct. 2022, 17:00 GDBOI101 ***@***.***> a scris:

**Comment by NrgCristi** [comment]
thanks @GDBOI101
